<?php

// Decodes the assets parameter and dumps the data
$dump = $this->asset()->decode( $this->assets )->dump();

// If nothing is dumped an exception is thrown
// @todo Generate a 404 page instead
if( empty( $dump ) )
  throw new Exception( 'Invalid asset' );

// Retrives the mime type of the dump
$finfo = finfo_open();
$mime  = finfo_buffer( $finfo, $dump, FILEINFO_MIME );
finfo_close( $finfo );

// Prints the correct header type and data
header( 'Content-Type: ' . $mime );
echo $dump;