<?php

// Decodes the assets parameter and dumps the assets data
$map  = $this->asset()->decodeAssets( $this->assets );
$dump = $this->asset()->dump( $map );

// If nothing is dumped an exception is thrown
if( empty( $dump ) )
  throw new Exception( 'Invalid asset' );

// Retrives the mime type of the dump
$finfo = finfo_open();
$mime  = finfo_buffer( $finfo, $dump, FILEINFO_MIME );
finfo_close( $finfo );

// Prints the correct header type and data
header( 'Content-Type: ' . $mime );
echo $dump;